version: '3'
services:
  student_service:
    image: ralucc12/student-service:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"
    run: |
      pip install -r requirements.txt
      python -m swagger_server &
      sleep 5 

  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"
    options: >-
      --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5